TaskManager/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('verification/', include('verify_email.urls')),
    path('', include('task.urls')),
    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

task/urls.py
from django.urls import path
from .views import HomePageView, TaskList, NewTaskView, TaskUpdateView, TaskDeleteView,TodayTaskList


app_name = 'task'
urlpatterns = [
    path('',HomePageView.as_view(), name='home'),
    path('task', TaskList.as_view(), name='tasks'),
    path('today-task', TodayTaskList.as_view(), name='today-task'),    
    path('add-task', NewTaskView.as_view(), name='add-task'),
    path('update-task/<slug:slug>/', TaskUpdateView.as_view(), name='update-task'),
    path('delete-task/<slug:slug>/', TaskDeleteView.as_view(), name='delete-task'),

]

accounts/models.py
# accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class CustomUser(AbstractUser):
    # add additional fields in here

    def __str__(self):
        return self.email
    

task/models.py
from datetime import date
from datetime import timedelta
from django.utils.text import slugify
from django.urls import reverse
import string, random
from django.db import models
from TaskManager.settings import AUTH_USER_MODEL as User



def generate_random_slug():
    return ''.join(random.choice(string.digits) for _ in range(12))


# Create your models here.
class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=200,blank=False,null=False)
    description = models.TextField(blank=True, null=True)
    task_due_date = models.DateField(blank=True,null=True,default=date.today() + timedelta(days=1)) 
    task_due_time = models.TimeField(blank=True,null=True)     
    complete = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(max_length=255, unique=True)
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('task:tasks')
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title + '-' + generate_random_slug())
        super(Task, self).save(*args, **kwargs)

    class Meta:
        verbose_name = 'Task'
        ordering = ['user']
        get_latest_by = 'created_at'
        

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ('email',)

class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('email',) 

task/forms.py
from django import forms
from .models import Task

class TaskUpdateForm(forms.ModelForm):
    title = forms.CharField(max_length=100, widget= forms.TextInput
        (attrs={'placeholder':"Enter the task's title"}))
    description = forms.CharField(max_length=150, required=False, widget= forms.Textarea
        (attrs={'placeholder':"Enter the task's description"}))
    task_due_date = forms.DateField(
        label="Select the task's due date", required=False,
        widget=forms.widgets.DateInput(attrs={'type':'date'})
    )
    task_due_time = forms.TimeField(
        label="Select the task's due time", required=False,
        widget=forms.widgets.TimeInput(attrs={'type':'time'})
    )
    complete = forms.BooleanField(label='Completed this task?',
        required = False, widget=forms.widgets.CheckboxInput(attrs={'class': 'checkbox-inline'}),
    )
    
    class Meta(forms.ModelForm):
        model = Task
        fields = ('title', 'description','task_due_date','task_due_time','complete')


class TaskForm(forms.ModelForm):
    title = forms.CharField(max_length=100, widget= forms.TextInput
        (attrs={'placeholder':"Enter the task's title"}))
    description = forms.CharField(max_length=150, required=False, widget= forms.Textarea
        (attrs={'placeholder':"Enter the task's description"}))
    task_due_date = forms.DateField(
        label="Select the task's due date", required=False,
        widget=forms.widgets.DateInput(attrs={'type':'date'})
    )
    task_due_time = forms.TimeField(
        label="Select the task's due time", required=False,
        widget=forms.widgets.TimeInput(attrs={'type':'time'})
    )
    class Meta(forms.ModelForm):
        model = Task
        fields = ('title', 'description','task_due_date','task_due_time')

accounts/views.py
from django.shortcuts import render

# Create your views here.

task/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect, render
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import TemplateView, ListView
from django.views.generic.edit import UpdateView, DeleteView
from .models import Task
from .forms import TaskUpdateForm, TaskForm
from datetime import date
from django.db.models import Q
import time



class HomePageView(TemplateView):
    template_name = 'home.html'

class TaskList(LoginRequiredMixin, ListView):
    model = Task
    context_object_name= 'tasks'
    template_name = 'tasks_list.html'
    
 
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["tasks"] = context['tasks'].filter(user=self.request.user)
        context["uncompleted_tasks"] = context['tasks'].filter(complete=False).order_by('task_due_date','task_due_time').all()
        
        context["completed_tasks"] = context['tasks'].filter(complete=True).order_by('task_due_date','task_due_time').all()
        

        search_input = self.request.GET.get('search-area') or ''
        if search_input:
            context['uncompleted_tasks'] = context['uncompleted_tasks'].filter(title__icontains=search_input)

        context['search_input'] = search_input
        
        return context



    
    
class TodayTaskList(LoginRequiredMixin, ListView):
    model = Task
    context_object_name= 'tasks'
    template_name = 'today_task_list.html'
    
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["tasks"] = context['tasks'].filter(user=self.request.user)
        context["today_tasks"] = context['tasks'].filter(task_due_date=date.today())               
        
        search_input = self.request.GET.get('search-area') or ''
        if search_input:
            context['today_tasks'] = context['today_tasks'].filter(title__icontains=search_input)

        context['search_input'] = search_input
        
        return context
    
    
class NewTaskView(LoginRequiredMixin,View):
    form_class = TaskForm
    initial = {'key': 'value'}
    template_name = 'task_form.html'

    def get(self, request, *args, **kwargs):
        form = self.form_class(initial=self.initial)
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        form.instance.user = self.request.user #to set the owner of the task to the current user
        if form.is_valid():
            form.save()
            return redirect('task:tasks')

        return render(request, self.template_name, {'form': form})


class TaskUpdateView(LoginRequiredMixin,UpdateView):
    model = Task 
    form_class = TaskUpdateForm
    template_name = 'task_update.html'
    #template_name = 'task-update-test.html'
    #success_url = reverse_lazy('task:tasks')
    
    
class TaskDeleteView(LoginRequiredMixin,DeleteView):
    model = Task
    context_object_name= 'task'
    template_name = 'task_delete.html'
    success_url = reverse_lazy('task:tasks')

templates/base.html
{% load crispy_forms_tags %}
<!DOCTYPE html>

<html lang="en">
    {% csrf_token %}
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    {% load crispy_forms_tags %}

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TaskManager</title>
    <style>
        .collapsing_button {
        color: rgba(18, 18, 19, 0.781);
        background-color: #eee;
        cursor: pointer;
        padding: 5px;
        width: 100%;
        border: none;
        text-align: left;
        outline: none;
        font-size: 20px;
        }

        /* Add a background color to the button if it is clicked on (add the .active class with JS), and when you move the mouse over it (hover) */
        .active, .collapsing_button:hover {
        background-color: #ccc;
        }
    </style>
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-dark  " style="background-color: blue; position:fixed; top:0;  width: 100%; z-index:10">

        <a class="navbar-brand" style="margin-left: 5%;" href="{% url 'task:tasks'  %}"><h4> Tasker</h4></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup" style="justify-content:right; padding-right: 8%;">
            <div class="navbar-nav">
                <ul class="navbar-nav mr-auto mt-2 mt-lg-0" style="margin-left: 20px; ">
                    <li class= "nav-item active"  > <a class="nav-link active" style="background-color: blue;" href={% url 'task:tasks' %}>Tasks </a> </li>
                    <li class= "nav-item active"  > <a class="nav-link active" style="background-color: blue;"href={% url 'task:today-task'%}> Today Tasks </a> </i>
                    <li class="nav-item active" style="padding-left: 10px; background-color: blue;" >
                    <div class="dropdown show">
                        <a class="navbar-brand" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="false">
                            <i class="bi bi-person-circle"></i>
                            hi {{user.username}}
                        </a>
                    
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                            <a class="dropdown-item" href={% url 'account_logout' %}>Sign Out</a>
                            <a class="dropdown-item" href={% url 'account_reset_password' %}>Reset Password </a>
                            <a class="dropdown-item" href="#">Incoming </a>
                        </div>
                    </div>
                    </li>
                    
                </ul>
                </div>
        </div>
    </nav>
    <br/>
    <br/>
    <div style="margin-top:10px;">


            {% block content %}

            {% endblock content %}

            {% include "task_form.html" %}
            {% include "task_update.html" %}
            {% include "task_delete.html" %}

        </div>
    </div>

</body>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>
<script>
    const basicAutocomplete = document.querySelector('#search-autocomplete');
    const data = ['One', 'Two', 'Three', 'Four', 'Five'];
    const dataFilter = (value) => {
        return data.filter((item) => {
            return item.toLowerCase().startsWith(value.toLowerCase());
        });
    };

    new mdb.Autocomplete(basicAutocomplete, {
        filter: dataFilter
    });
</script>

</html>

templates/base2.html
{% load crispy_forms_tags %}
<!DOCTYPE html>

<html lang="en">

<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    {% load crispy_forms_tags %}

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TaskManager</title>

</head>

<body>
    <nav class="navbar navbar-expand-md navbar-dark  " style="background-color: blue; position:fixed; top:0;  width: 100%; z-index:10">

        <a class="navbar-brand" style="margin-left: 5%;" href="{% url 'task:tasks'  %}"><h4> Tasker</h4></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
       
    </nav>
    <br/>
    <br/>
    <div style="margin-top:10px;">


            {% block content %}

            {% endblock content %}

        

        </div>
    </div>

</body>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>

</html>

templates/completed_task_list.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}
<div style="margin-top:50px" class=" container ">

    <h3>Completed Tasks</h3>


    <form method="GET" >
        <div class="form-group">
            <input  type='text' class="form-control" name='search-area' placeholder="Search for a task..." value="{{search_input}}">
        </div>
    </form>
    <br>
    <div class="container">
        <div class="row">
            <ul>
                {% for task in completed_tasks %}
                <div class="col-sm">
                    <div class="card" style="width: auto;">
    
                        <div class="card-body">
                            <div class="row" style="margin-left: auto;">
                                <div class="col-8">
                                    <h6 class="card-title"> {{task.title|capfirst|truncatechars:20 }}</h6>
                                    <p style="color:rgb(85, 82, 82);" class="card-text"> {{task.description|truncatechars:20}}</p>
                                </div>
    
                                <div class="col-4">
                                    <a style="margin-left: 10px;"><i class="bi bi-trash3-fill"
                                            style="font-size: 1.5rem; color: orangered;" data-toggle="modal"
                                            data-target="#deleteModal{{ task.slug }}"></i></a>
    
                                    <a style="margin-left: 10px;"><i class="bi bi-pencil-square"
                                            style="font-size: 1.5rem; color: gray;" data-toggle="modal"
                                            data-target="#editModal{{ task.slug }}"></i></a>
    
                                </div>
                                <br>
                                <div style="margin-top: 5px;"><i class="bi bi-calendar-week" style="font-size: 13px;">{% if task.task_due_date %} {{task.task_due_date}} {% else %} No due date {% endif %}</i> {%if task.task_due_date %} &nbsp || &nbsp {% if task.task_due_time %}<i class="bi bi-clock" style="font-size: 13px;">{{task.task_due_time}}</i></div> {% else %} {% endif %} {% else %} {% endif %} 
                            </div>
    
    
                        </div>
                    </div>
                </div>
                {% include "task_update.html" %}
                {% include "task_delete.html" %}
                <br>
                {% empty %}
                <li>No tasks Completed.</li>
    
    
                {% endfor %}
            </ul>
        </div>
    </div>

</div>
{% endblock content %}

templates/home.html
{% load static %}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">

<head>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
  
  {% load crispy_forms_tags %}

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>TaskManager</title>

</head>

<body>
  <nav class="navbar navbar-expand-md navbar-dark  "
    style="background-color: blue; width: 100%; z-index:10">

    <a class="navbar-brand" style="margin-left: 5%;" href="{% url 'task:tasks'  %}">Tasker</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
      aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    </div>
  </nav>

  <div style="margin-top:10px;">
    <div class="container">



      {% if user.is_authenticated %}
        Hi {{ user.username }}!
      <p><a href="{% url 'account_logout' %}">Log Out</a></p>
      {% else %}
      <div
        style=" padding-bottom: 100px; margin: 0; position: absolute; top: 50%; -ms-transform: translateY(-50%);transform: translateY(-50%)">

        <div class="row">

          <div class=" col-md d-flex align-items-center justify-content-center">
            <div class="text-center " style="margin-left:10px ; margin-right:10px ;">
              <img src="{% static 'public/img/homepage_image.png' %}" class="img-fluid" alt="some random image">
            </div>

          </div>

          <div class=" col-md d-flex align-items-center justify-content-center">
            <div class="text-center " style="margin-left:10px ; margin-right:10px ;">
              <h5 style="padding-left: 10%; padding-right: 10%;">This is an application that helps you keeps track of
                your tasks.
                You are not logged in, please press sign up to register
                or login to sign in if you already have an account </h5>
              <br>
              <a href="{% url 'account_login' %}"> <button style="width:100px;" type="submit" class="btn btn-primary">
                  Login
                </button> </a>

              <a href="{% url 'account_signup' %}"><button style="margin-left: 10px;width:100px; " type="submit"
                  class="btn btn-primary">
                  Sign Up
                </button></a>

            </div>
          </div>

        </div>

      </div>




      {% endif %}




      <footer class="text-center text-white"
        style="position: fixed; bottom: 0;left: 0;  width: 100%; background-color: blue;">
        <!-- Grid container -->
        <div class="container pt-4">
          <!-- Section: Social media -->
          <section class="mb-4">
            <!-- Facebook -->
            <a class="btn btn-link btn-floating btn-lg text-light m-1" href="#!" role="link"
              data-mdb-ripple-color="dark"><i class="bi bi-facebook"></i></a>

            <!-- Twitter -->
            <a class="btn btn-link btn-floating btn-lg text-light m-1" href="https://twitter.com/Emerald_d_great" target="_blank" rel="noopener noreferrer" role="link"
              data-mdb-ripple-color="dark"><i class="bi bi-twitter"></i></a>

            <!-- Github -->
            <a class="btn btn-link btn-floating btn-lg text-light m-1" href="https://github.com/emeralddd123" target="_blank" rel="noopener noreferrer" role="link"
              data-mdb-ripple-color="dark"><i class="bi bi-github"></i></a>
          </section>
          <!-- Section: Social media -->
        </div>
        <!-- Grid container -->

        <!-- Copyright -->
        <div class="text-center text-light p-3">
          © 2022 Copyright:
          <a class="text-light" href="#">Emerald</a>
        </div>
        <!-- Copyright -->
      </footer>


    </div>
  </div>

</body>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
  integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
  integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"
  integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</html>

templates/task-update-test.html
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="" method="post">
        {% csrf_token %}
        {{ form | crispy }}
    </form>
</body>
</html>

templates/task_form.html
{% load crispy_forms_tags %}
<!-- Modal -->
<div class="modal fade" {% block modal-id %} id="addModal" {% endblock modal-id %} tabindex="-1" role="dialog" aria-labelledby="addModalLabel"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h6 class="modal-title" id="addModalLabel"> {% block modal-title %} <i class="bi bi-plus" ></i>&nbsp;&nbsp; Add Task {% endblock modal-title %} </h6>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            
                <div class="card">
                    
                    <div class="card-body">
                        <form {% block action %} action="/add-task" {% endblock action %} method="POST">
                            {% csrf_token %}
                            <div class="modal-body">
                            
                            {% block form-inputs %}
                            
                            
                            
                                <div id="div_id_title" class="mb-3"> <label for="id_title" class="form-label requiredField">
                                        Title<span class="asteriskField">*</span> </label> <input type="text" name="title"
                                        placeholder="Enter the task's title" maxlength="100" class="textinput textInput form-control" required=""
                                        id="id_title"> </div>
                                <div id="div_id_description" class="mb-3"> <label for="id_description" class="form-label">
                                        Description
                                    </label> <textarea name="description" cols="40" rows="6" placeholder="Enter the task's description"
                                        maxlength="150" class="textarea form-control" id="id_description"></textarea> </div>
                                <div id="div_id_task_due_date" class="mb-3"> <label for="id_task_due_date" class="form-label">
                                        Task's due date
                                    </label> <input type="date" name="task_due_date" class="dateinput form-control" id="id_task_due_date"> </div>
                                <div id="div_id_task_due_time" class="mb-3"> <label for="id_task_due_time" class="form-label">
                                        Task's due time
                                    </label> <input type="time" name="task_due_time" class="timeinput form-control" id="id_task_due_time"> </div>
                            
                                <button style="margin-left: 15px;" type="button" class="btn btn-danger"><a href="/task"
                                        style="text-decoration: none; color: white;" box-shadow="none">Cancel</a></button>
                                <button type="submit" class="btn btn-success" box-shadow="none">Add</button>
                            
                            {% endblock form-inputs %}
                            
                            </div>
                        </form>
                    </div>
                </div>
            
        </div>
    </div>
</div>

templates/task_update.html
{% load crispy_forms_tags %}
<!-- Modal -->
<div class="modal fade" {% block modal-id %} id="editModal{{ task.slug }}" {% endblock modal-id %} tabindex="-1" role="dialog" aria-labelledby="editModalLabel"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h6 class="modal-title" id="editModalLabel"> {% block modal-title %} <i class="bi bi-pencil-square" ></i>&nbsp;&nbsp; Edit Task {% endblock modal-title %} </h6>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            
                <div class="card">
                    
                    <div class="card-body">
                        <form {% block action %} action="/update-task/{{task.slug}}/" {% endblock action %} method="POST">
                            {% csrf_token %}
                            <div class="modal-body">
                            
                            
                            
                                <div id="div_id_title" class="mb-3"> <label for="id_title" class="form-label requiredField">
                                        Title<span class="asteriskField">*</span> </label> <input type="text" name="title"
                                        value="{{task.title|capfirst|truncatechars:20}}" placeholder="Enter the task's title" maxlength="100"
                                        class="textinput textInput form-control" required=" " id="id_title"> </div>
                                <div id="div_id_description" class="mb-3"> <label for="id_description" class="form-label">
                                        Description
                                    </label> <textarea name="description" cols="40" rows="6" placeholder="Enter the task's description"
                                        maxlength="150" class="textarea form-control" id="id_description">{{task.description}}</textarea>
                                </div>
                                <div id="div_id_task_due_date" class="mb-3"> <label for="id_task_due_date" class="form-label">
                                        Task's due date
                                    </label> <input type="date" name="task_due_date" value="{{task.task_due_date}}" class="dateinput form-control"
                                        id="id_task_due_date"> </div>
                                <div id="div_id_task_due_time" class="mb-3"> <label for="id_task_due_time" class="form-label">
                                        Task's due time
                                    </label> <input type="time" name="task_due_time"   class="timeinput form-control"
                                        id="id_task_due_time" value="{{task.task_due_time}}"> </div>
                                <div class="mb-3">
                                    <div id="div_id_complete" class="mb-3"> <input type="checkbox" name="complete"
                                            class="checkbox-inline checkboxinput form-check-input" id="id_complete"  value=" {% if task.complete %}True{% else %}False{% endif %} " {% if task.complete %}checked{% endif %}> <label for="id_complete"
                                            class="form-check-label">
                                            Completed this task?
                                        </label> </div>
                                </div>
                                <button style="margin-left: 15px;" type="button" class="btn btn-danger"><a href="/task"
                                        style="text-decoration: none; color: white;" box-shadow="none">Cancel</a></button> 
                                <button type="submit" class="btn btn-success" box-shadow="none">Update</button>

                            
                            </div>
                        </form>
                    </div>
                </div>
            
        </div>
    </div>
</div>

templates/today_task_list.html
{% extends "base.html" %}

{% load crispy_forms_tags %}



{% block content %}
<div style="margin-top:50px" class=" container ">

    <h3>Today Tasks</h3>
    <form method="GET">
        <div class="form-group">
            <input type='text' class="form-control" name='search-area' placeholder="Search for a task..." value="{{search_input}}">
        </div>
    </form>
    <br>
    <div class="container">
        <div class="row">
            <ul>
                {% for task in today_tasks %}
                <div class="col-sm">
                    <div class="card" style="width: auto;">

                        <div class="card-body">
                            <h5 class="card-title">{{task.title }}</h5>
                            <p class="card-text">{{task.description }}</p>
                            <a href="/delete-task/{{task.slug}}" class="btn btn-danger">Delete</a> <a
                                style="margin-left: 10px;" href="/update-task/{{task.slug}}"
                                class="btn btn-success">Update</a>
                        </div>
                    </div>
                </div>
                <br>
                {% empty %}
                <li>No tasks is set for today.</li>
                {% endfor %}
            </ul>
        </div>
    </div>

</div>
{% endblock content %}